# Generated by Django 2.2.1 on 2019-09-24 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('aplicants_name', models.CharField(max_length=50)),
                ('directory', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=10)),
                ('length', models.CharField(max_length=10)),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2019, 9, 24, 6, 4, 48, 791417, tzinfo=utc))),
                ('convert_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('aplicants_name', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=10)),
                ('convert_date', models.DateTimeField(blank=True, null=True)),
                ('graded_date', models.DateTimeField(blank=True, null=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='django_app.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_score', models.CharField(max_length=3)),
                ('b_score', models.CharField(max_length=3)),
                ('c_score', models.CharField(max_length=3)),
                ('d_score', models.CharField(max_length=3)),
                ('e_score', models.CharField(max_length=3)),
                ('f_score', models.CharField(max_length=3)),
                ('g_score', models.CharField(max_length=3)),
                ('h_score', models.CharField(max_length=3)),
                ('i_score', models.CharField(max_length=3)),
                ('final_score', models.CharField(max_length=15)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='django_app.Text')),
            ],
        ),
    ]
