# Generated by Django 2.2.1 on 2019-09-24 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='full_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='audio',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 6, 37, 21, 721863, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
