# Generated by Django 2.2.1 on 2019-09-26 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20190924_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 26, 11, 8, 37, 269273, tzinfo=utc)),
        ),
    ]
